CREATE TABLE REPOSITORIO(
	id_palavra serial PRIMARY KEY,
	palavra varchar(5) not null UNIQUE
);

select * from REPOSITORIO;

SELECT PALAVRA FROM REPOSITORIO WHERE ID_PALAVRA = (SELECT floor(random() * 600 + 1))

-- ALTER TABLE REPOSITORIO ADD COLUMN INATIVA BOOLEAN DEAFAULT FALSE;

ALTER TABLE REPOSITORIO ADD COLUMN INATIVA TIMESTAMP;

DO $$
DECLARE
	resultado INTEGER;

BEGIN
	SELECT id_palavra FROM REPOSITORIO WHERE ID_PALAVRA = (SELECT floor(random() * + 1)) INTO resultado;
	UPDATE REPOSITORIO SET INATIVA = NOW() WHERE id_palavra = resultado;
END $$;


SELECT * FROM REPOSITORIO
ORDER BY INATIVA;


UPDATE repositorio
SET inativa = null;

select * from repositorio

